[package]
name = "rtmonitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.2"
rand = "^0.8"
ssh2 = "^0.9.3"

